using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Drawing;
using System.Drawing.Imaging;
using System.Linq;
using System.Runtime.InteropServices;
using System.Windows.Forms;
using Emgu.CV;
using Emgu.CV.CvEnum;
using Emgu.CV.Dnn;
using Emgu.CV.Structure;
using Emgu.CV.Util;
using SpinnakerNET;
using SpinnakerNET.GenApi;
using System.Drawing.Drawing2D;

namespace CSharp_Bumblebee
{
    public partial class Form1 : Form
    {
        [DllImport("kernel32", SetLastError = true, CharSet = CharSet.Auto)] private static extern bool SetDllDirectory(string dllPathName);
        private Panel titleBar; private Label titleLabel; private Button closeButton; private Button connectBtn; private Button startBtn; private Button minimizeButton;
        IManagedCamera cam; bool connected=false,started=false,capImg,capImgComplete; StereoCameraParameters stereoCameraParameters; List<ColorClass> colorList; List<byte[]> colorArr; double fontSize; int circleSize,fontThick;
        const int YoloSize=640; const float ConfidenceThreshold=.50f; const float NmsThreshold=.45f;
        class ColorClass{public byte B;public byte G;public byte R;}
        [DllImport("user32.dll")] public static extern bool ReleaseCapture(); [DllImport("user32.dll")] public static extern int SendMessage(IntPtr hWnd,int Msg,int wParam,int lParam);
        [DllImport("Gdi32.dll",EntryPoint="CreateRoundRectRgn")] private static extern IntPtr CreateRoundRectRgn(int a,int b,int c,int d,int e,int f);
        private void TitleBar_MouseDown(object sender,MouseEventArgs e){ReleaseCapture();SendMessage(Handle,0xA1,0x2,0);}
        public Form1(){if(!SetDllDirectory(@"..\Libraries"))throw new Win32Exception();ManagedSystem system=new ManagedSystem();ManagedCameraList camList=system.GetCameras();if(camList.Count==0){camList.Clear();system.Dispose();MessageBox.Show("No cameras Detected!");Environment.Exit(Environment.ExitCode);}else cam=camList[0];stereoCameraParameters=new StereoCameraParameters();colorList=new List<ColorClass>();colorArr=new List<byte[]>();for(int i=0;i<ushort.MaxValue;i++){colorArr.Add(new byte[3]);colorList.Add(new ColorClass());}FormBorderStyle=FormBorderStyle.None;StartPosition=FormStartPosition.CenterScreen;Size=new Size(400,300);BackColor=Color.White;Padding=new Padding(1);Load+=(s,e)=>Region=Region.FromHrgn(CreateRoundRectRgn(0,0,Width,Height,20,20));InitializeTitleBar();InitializeBody();InitializeComponent();pBoxLogo.Image=Bitmap.FromFile("APO_LOGO2.jpg");}
        private void InitializeTitleBar(){titleBar=new Panel(){Dock=DockStyle.Top,Height=40,BackColor=Color.FromArgb(33,150,243)};titleBar.MouseDown+=TitleBar_MouseDown;Controls.Add(titleBar);titleLabel=new Label(){Text="Teledyne FLIR BumbleBee Demo",ForeColor=Color.White,Font=new Font("Segoe UI",12,FontStyle.Bold),Location=new Point(10,10),AutoSize=true};titleBar.Controls.Add(titleLabel);closeButton=new Button(){Text="✕",FlatStyle=FlatStyle.Flat,ForeColor=Color.White,BackColor=Color.Transparent,Size=new Size(40,40),Dock=DockStyle.Right};closeButton.FlatAppearance.BorderSize=0;closeButton.Click+=(s,e)=>Close();titleBar.Controls.Add(closeButton);minimizeButton=new Button(){Text="—",FlatStyle=FlatStyle.Flat,ForeColor=Color.White,BackColor=Color.Transparent,Size=new Size(40,40),Dock=DockStyle.Right};minimizeButton.FlatAppearance.BorderSize=0;minimizeButton.Click+=(s,e)=>WindowState=FormWindowState.Minimized;titleBar.Controls.Add(minimizeButton);}
        private void InitializeBody(){connectBtn=new Button(){Text="連線",Size=new Size(120,40),Location=new Point((ClientSize.Width-300)/2,80),BackColor=Color.FromArgb(33,150,243),ForeColor=Color.White,FlatStyle=FlatStyle.Flat};connectBtn.Click+=connectBtn_Click;Controls.Add(connectBtn);startBtn=new Button(){Text="開始取像",Size=new Size(120,40),Location=new Point(ClientSize.Width/2,80),BackColor=Color.FromArgb(33,150,243),ForeColor=Color.White,FlatStyle=FlatStyle.Flat,Enabled=false};startBtn.Click+=startBtn_Click;Controls.Add(startBtn);}
        private void GetStereoParameter(StereoCameraParameters p,INodeMap n){p.coordinateOffset=(float)n.GetNode<IFloat>("Scan3dCoordinateOffset").Value;p.baseline=(float)n.GetNode<IFloat>("Scan3dBaseline").Value;p.focalLength=(float)n.GetNode<IFloat>("Scan3dFocalLength").Value;p.principalPointU=(float)n.GetNode<IFloat>("Scan3dPrincipalPointU").Value;p.principalPointV=(float)n.GetNode<IFloat>("Scan3dPrincipalPointV").Value;p.disparityScaleFactor=(float)n.GetNode<IFloat>("Scan3dCoordinateScale").Value;p.invalidDataFlag=n.GetNode<IBool>("Scan3dInvalidDataFlag").Value;p.invalidDataValue=(float)n.GetNode<IFloat>("Scan3dInvalidDataValue").Value;}
        private void SetBufferHandingMode(INodeMap n){n.GetNode<IEnum>("StreamBufferHandlingMode").Value=StreamBufferHandlingModeEnum.NewestOnly.ToString();}
        private void connectBtn_Click(object sender,EventArgs e){if(!connected){cam.Init();INodeMap n=cam.GetNodeMap();for(int i=0;i<5;i++)SetBufferHandingMode(cam.GetTLStreamNodeMap(i));ResoultionCheck(n);GetStereoParameter(stereoCameraParameters,n);connectBtn.Text="斷線";startBtn.Enabled=true;connected=true;}else{cam.DeInit();connectBtn.Text="連線";startBtn.Enabled=false;connected=false;}}
        private void startBtn_Click(object sender,EventArgs e){if(!started){capImg=true;capImgComplete=false;cam.BeginAcquisition();backgroundWorker1.RunWorkerAsync();startBtn.Text="停止取像";connectBtn.Enabled=false;started=true;}else{capImg=false;startBtn.Enabled=false;}}
        private void ResoultionCheck(INodeMap n){IEnum r=n.GetNode<IEnum>("StereoResolution");if(r.ToString()=="Full"){circleSize=5;fontSize=1;fontThick=2;}else if(r.ToString()=="Quarter"){circleSize=3;fontSize=.5;fontThick=1;}else{circleSize=4;fontSize=.8;fontThick=2;}}
        public delegate void InvokeDelegate(Bitmap bmp,int imgWidth,int imgHeight);
        private void backgroundWorker1_DoWork(object sender,DoWorkEventArgs e){Net net=DnnInvoke.ReadNetFromONNX("yolov8n.onnx");try{net.SetPreferableBackend(Backend.Cuda);net.SetPreferableTarget(Target.Cuda);}catch{net.SetPreferableBackend(Backend.OpenCV);net.SetPreferableTarget(Target.Cpu);}IManagedImageList imageList=new ManagedImageList();Mat disparityMat8Bit=new Mat();IManagedImage rectifiedImg=new ManagedImage();IManagedImage disparityImg=new ManagedImage();try{while(capImg){imageList=cam.GetNextImageSync(3000);IManagedImage ro=imageList.GetByPayloadType(ImagePayloadType.IMAGE_PAYLOAD_TYPE_RECTIFIED_SENSOR1);IManagedImage d=imageList.GetByPayloadType(ImagePayloadType.IMAGE_PAYLOAD_TYPE_DISPARITY_SENSOR1);if(ro==null||d==null||ro.IsIncomplete||d.IsIncomplete){imageList.Release();continue;}rectifiedImg.DeepCopy(ro);disparityImg.DeepCopy(d);ro.Dispose();d.Dispose();imageList.Release();int w=(int)rectifiedImg.Width,h=(int)rectifiedImg.Height,stride=(int)rectifiedImg.Stride;using(Mat bgr=new Mat())using(Mat rgb=new Mat(h,w,DepthType.Cv8U,3,rectifiedImg.DataPtr,0)){CvInvoke.CvtColor(rgb,bgr,ColorConversion.Rgb2Bgr);unsafe{PersionDetect(net,(ushort*)disparityImg.NativeData,ref bgr,ref disparityMat8Bit);}using(Bitmap bmp=new Bitmap(w,h,stride,PixelFormat.Format24bppRgb,bgr.DataPointer)){pBox.BeginInvoke(new InvokeDelegate(InvokeDisplay),new Bitmap(bmp),w,h);}}}}finally{net.Dispose();disparityMat8Bit.Dispose();rectifiedImg.Dispose();disparityImg.Dispose();capImgComplete=true;BeginInvoke(new Action(()=>{try{cam.EndAcquisition();}catch{}startBtn.Text="開始取像";startBtn.Enabled=true;connectBtn.Enabled=true;started=false;}));}}
        private Mat Letterbox(Mat src,out float scale,out int padX,out int padY){scale=Math.Min(YoloSize/(float)src.Width,YoloSize/(float)src.Height);int nw=(int)Math.Round(src.Width*scale),nh=(int)Math.Round(src.Height*scale);padX=(YoloSize-nw)/2;padY=(YoloSize-nh)/2;Mat dst=new Mat(YoloSize,YoloSize,DepthType.Cv8U,3);dst.SetTo(new MCvScalar(114,114,114));using(Mat resized=new Mat()){CvInvoke.Resize(src,resized,new Size(nw,nh));using(Mat roi=new Mat(dst,new Rectangle(padX,padY,nw,nh)))resized.CopyTo(roi);}return dst;}
        unsafe private void PersionDetect(Net net,ushort* disparityData,ref Mat mat,ref Mat disparityMat){float scale;int padX,padY;using(Mat input=Letterbox(mat,out scale,out padX,out padY))using(Mat blob=DnnInvoke.BlobFromImage(input,1/255.0,new Size(YoloSize,YoloSize),new MCvScalar(),true,false)){net.SetInput(blob);using(Mat output=net.Forward())using(Mat reshaped=output.Reshape(1,84))using(Mat transposed=new Mat()){CvInvoke.Transpose(reshaped,transposed);List<Rectangle> boxes=new List<Rectangle>();List<float> scores=new List<float>();float* p=(float*)transposed.DataPointer.ToPointer();int rows=transposed.Rows,cols=transposed.Cols;for(int i=0;i<rows;i++,p+=cols){float personScore=p[4];if(personScore<ConfidenceThreshold)continue;float cx=(p[0]-padX)/scale,cy=(p[1]-padY)/scale,w=p[2]/scale,h=p[3]/scale;Rectangle r=ClampRect(new Rectangle((int)(cx-w/2),(int)(cy-h/2),(int)w,(int)h),mat.Width,mat.Height);if(r.Width>2&&r.Height>2){boxes.Add(r);scores.Add(personScore);}}if(boxes.Count==0)return;using(VectorOfRect bv=new VectorOfRect(boxes.ToArray()))using(VectorOfFloat sv=new VectorOfFloat(scores.ToArray()))using(VectorOfInt indices=new VectorOfInt()){DnnInvoke.NMSBoxes(bv,sv,ConfidenceThreshold,NmsThreshold,indices);foreach(int i in indices.ToArray()){Rectangle rect=boxes[i];double z=ComputeZvalue(rect,disparityData,mat.Width,mat.Height);Point c=new Point(rect.X+rect.Width/2,rect.Y+rect.Height/2);CvInvoke.Rectangle(mat,rect,new MCvScalar(0,255,0),2);CvInvoke.Circle(mat,c,circleSize,new MCvScalar(255,0,0),-1);if(z>0)CvInvoke.PutText(mat,z.ToString("f2")+"m",c,FontFace.HersheyTriplex,fontSize,new Bgr(255,255,255).MCvScalar,fontThick);}}}}}
        private Rectangle ClampRect(Rectangle r,int width,int height){int l=Math.Max(0,r.Left),t=Math.Max(0,r.Top),rr=Math.Min(width,r.Right),bb=Math.Min(height,r.Bottom);return rr>l&&bb>t?Rectangle.FromLTRB(l,t,rr,bb):Rectangle.Empty;}
        unsafe private double ComputeZvalue(Rectangle person,ushort* disparityData,int imgWidth,int imgHeight){Rectangle r=ClampRect(person,imgWidth,imgHeight);if(r.IsEmpty)return 0;int roiW=Math.Max(1,(int)(r.Width*.45));int roiH=Math.Max(1,(int)(r.Height*.45));int left=r.X+(r.Width-roiW)/2;int top=r.Y+(int)(r.Height*.25);Rectangle roi=ClampRect(new Rectangle(left,top,roiW,roiH),imgWidth,imgHeight);List<double> z=new List<double>(Math.Max(32,roi.Width*roi.Height/16));for(int y=roi.Top;y<roi.Bottom;y+=2)for(int x=roi.Left;x<roi.Right;x+=2){ushort raw=disparityData[y*imgWidth+x];if(raw==0)continue;if(stereoCameraParameters.invalidDataFlag&&Math.Abs(raw-stereoCameraParameters.invalidDataValue)<.5)continue;double disp=raw*stereoCameraParameters.disparityScaleFactor+stereoCameraParameters.coordinateOffset;if(disp<=0)continue;double v=stereoCameraParameters.focalLength*stereoCameraParameters.baseline/disp;if(v>0&&v<100000)z.Add(v);}return GetMedianInPlace(z);}
        private double GetMedianInPlace(List<double> v){if(v==null||v.Count==0)return 0;v.Sort();int m=v.Count/2;return v.Count%2==0?(v[m-1]+v[m])*.5:v[m];}
        private void InvokeDisplay(Bitmap bmp,int imgWidth,int imgHeight){Bitmap old=pBox.Image as Bitmap;pBox.Image=bmp;pBox.Width=imgWidth;pBox.Height=imgHeight;old?.Dispose();}
        private void Form1_FormClosing(object sender,FormClosingEventArgs e){capImg=false;try{if(started)cam.EndAcquisition();}catch{}try{if(connected)cam.DeInit();}catch{}cam?.Dispose();}
        private void backgroundWorker1_RunWorkerCompleted(object sender,RunWorkerCompletedEventArgs e){}
    }
    public class StereoCameraParameters{public float coordinateOffset;public float baseline;public float focalLength;public float principalPointU;public float principalPointV;public float disparityScaleFactor;public bool invalidDataFlag;public float invalidDataValue;}
}
